joint_mappings:
  - joint: "Joint_1"
    axis: 0
    min_velocity: -1.0
    max_velocity: 1.0
    invert: false

  - joint: "Joint_2"
    axis: 1
    min_velocity: -1.0
    max_velocity: 1.0
    invert: false

  - joint: "Joint_3"
    axis: 2
    min_velocity: -1.0
    max_velocity: 1.0
    invert: false

  - joint: "Joint_4"
    axis: 5
    min_velocity: -1.0
    max_velocity: 1.0
    invert: false    

  - joint: "Joint_5"
    axis: 5
    min_velocity: -1.0
    max_velocity: 1.0
    invert: false   